Added hashing password
VladOSTAFI/skad-fitness pull request #4
Opened 2023-05-12 19:15 UTC by Enrikokokoko

2023-05-13 16:53 UTC, VladOSTAFI requested changes

2023-05-13 16:53 UTC, VladOSTAFI commented on src/auth/auth.service.ts
> +      accessToken: await this.jwtService.signAsync(payload),
Please add const `accessToken` next to `refreshToken` and use it here.

2023-05-13 16:53 UTC, VladOSTAFI commented on src/auth/auth.service.ts
> +    const hash = createHash('sha256').update(password).digest('hex')
I think it would be better to rename this variable to `hashedPassword`

2023-05-13 16:53 UTC, VladOSTAFI commented on src/auth/auth.service.ts
> +    if(user! || user.password != hash) {
could you explain me what does `user!` mean?

2023-05-13 16:53 UTC, VladOSTAFI commented on src/user/user.service.ts
> +    password = createHash('sha256').update(username).digest('hex')
why do you reassign new value to `password` variable instead of creating new variable?

2023-05-13 17:46 UTC, Enrikokokoko commented on src/auth/auth.service.ts
> +    if(user! || user.password != hash) {
check for existing user

2023-05-13 17:51 UTC, Enrikokokoko commented on src/user/user.service.ts
> +    password = createHash('sha256').update(username).digest('hex')
I don't even know what to say

2023-05-13 17:52 UTC, Enrikokokoko commented on src/auth/auth.service.ts
> +    const hash = createHash('sha256').update(password).digest('hex')
done

2023-05-13 17:52 UTC, Enrikokokoko commented on src/auth/auth.service.ts
> +      accessToken: await this.jwtService.signAsync(payload),
done

2023-05-13 18:01 UTC, Enrikokokoko commented on src/auth/auth.service.ts
> +    if(user! || user.password != hash) {
Exactly, sign must be placed at start)

2023-05-15 09:52 UTC, VladOSTAFI commented on src/auth/auth.service.ts
> +    if(user! || user.password != hash) {
I would suggest to remove check `user.password != hash`, because of you are searching by username and password here `const user = await this.userModel.findOne({ username, password: hash})`.
So user will not be returned in case password is not correct.

2023-05-15 12:09 UTC, Enrikokokoko commented on src/user/user.service.ts
> +    password = createHash('sha256').update(username).digest('hex')
done

2023-05-15 15:58 UTC, VladOSTAFI approved these changes

2023-05-15 16:12 UTC, merged