Refreshtoken and accesstoken
VladOSTAFI/skad-fitness pull request #5
Opened 2023-05-14 21:47 UTC by Enrikokokoko

2023-05-15 09:58 UTC, VladOSTAFI requested changes

2023-05-15 09:58 UTC, VladOSTAFI commented on src/app.module.ts
> +    connectionName:  'auth'
Why do you use `connectionName` in that case?

2023-05-15 09:58 UTC, VladOSTAFI commented on src/app.module.ts
> +  MongooseModule.forRoot(DB_URL, {
Why do you create new connection to database here?

2023-05-15 09:58 UTC, VladOSTAFI commented on src/auth/auth.module.ts
> +        signOptions: { expiresIn: '60s' }
Please move '60s' to env variables

2023-05-15 09:58 UTC, VladOSTAFI commented on src/user/user.module.ts
> +    MongooseModule.forFeature([{ name: User.name, schema: UserSchema }], 'user'),
Why do you pass 'user' argument here?

2023-05-15 14:29 UTC, Enrikokokoko commented on src/app.module.ts
> +  MongooseModule.forRoot(DB_URL, {
service didn't start

2023-05-15 14:31 UTC, Enrikokokoko commented on src/user/user.module.ts
> +    MongooseModule.forFeature([{ name: User.name, schema: UserSchema }], 'user'),
service didn't start without argument 'user'

2023-05-15 14:34 UTC, Enrikokokoko commented on src/auth/auth.module.ts
> +        signOptions: { expiresIn: '60s' }
done

2023-05-16 19:31 UTC, VladOSTAFI approved these changes

2023-05-16 19:31 UTC, merged