Get userdata
VladOSTAFI/skad-fitness pull request #6
Opened 2023-05-16 14:56 UTC by Enrikokokoko

2023-05-16 19:39 UTC, VladOSTAFI requested changes

2023-05-16 19:39 UTC, VladOSTAFI commented on src/user/user.service.ts
> +      throw new HttpException('UserId not found', HttpStatus.BAD_REQUEST)
Error message is not descriptive.
Change it to _User entity is not found._

2023-05-17 10:37 UTC, Enrikokokoko commented on src/auth/constants.ts
> +export const jwtConstants = {
jwtCONSTANTS или JwtConstants?

2023-05-17 17:39 UTC, VladOSTAFI approved these changes

2023-05-17 17:40 UTC, merged